language: go
go:
- 1.10.x

env:
- DEP_VERSION=0.5.1

before_script:
- curl -L -s https://github.com/golang/dep/releases/download/v${DEP_VERSION}/dep-linux-amd64
  -o $GOPATH/bin/dep
- chmod +x $GOPATH/bin/dep
- dep ensure -v --vendor-only

script:
- go vet ./...
- go test -v -cover -coverprofile=coverage.txt -covermode=atomic ./...

after_success:
- bash <(curl -s https://codecov.io/bash)
