language: go
go:
- 1.10.x

env:
- DEP_VERSION=0.5.1

cache:
  directories:
  - $GOPATH/pkg/dep/sources

before_script:
# install kubebuilder
- curl -L -O "https://github.com/kubernetes-sigs/kubebuilder/releases/download/v1.0.7/kubebuilder_1.0.7_linux_amd64.tar.gz"
- tar -zxvf kubebuilder_1.0.7_linux_amd64.tar.gz
- mkdir -p bin/ && mv kubebuilder_1.0.7_linux_amd64 bin/kubebuilder
# install dep
- curl -L -s https://github.com/golang/dep/releases/download/v${DEP_VERSION}/dep-linux-amd64
  -o $GOPATH/bin/dep
- chmod +x $GOPATH/bin/dep
- dep ensure -v --vendor-only

script:
- go vet ./pkg/... ./cmd/...
- KUBEBUILDER_ASSETS="$TRAVIS_BUILD_DIR/bin/kubebuilder/bin"
  go test -v -cover -coverprofile=coverage.txt -covermode=atomic ./pkg/... ./cmd/...

after_success:
- bash <(curl -s https://codecov.io/bash)
