apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: podrules.kuberule.chickenzord.com
spec:
  group: kuberule.chickenzord.com
  names:
    kind: PodRule
    plural: podrules
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            applyOrder:
              description: Arbitrary number to define ordering of multiple rules matching
                same pods. Higher number will be applied later, but might override
                mutations of smaller number.
              format: int32
              type: integer
            mutations:
              description: Mutations to be done on the selected pods
              properties:
                annotations:
                  description: Annotations to be merged with selected pods' existing
                    annotations
                  type: object
              type: object
            selector:
              description: Label selector for pods
              type: object
          required:
          - applyOrder
          type: object
        status:
          type: object
  version: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
